version: "3"
services:
  application:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - main_network
  db:
    container_name: db
    restart: always
    image: mysql:5.7.9
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d/:ro
    networks:
    - main_network
networks:
  main_network: